version: '3.8'

services:
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        networks:
            - nesjs-network
        volumes:
            - .:/src/app
            - /src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: nestjs_api_prod
        image: nestjs-api-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        networks:
            - nesjs-network
        volumes:
            - .:/src/app
            - /src/app/node_modules
        restart: unless-stopped

networks:
    nesjs-network: